branch-defaults:
  master:
    environment: production
    group_suffix: null
global:
  application_name: idt-production
  branch: staing
  default_ec2_keyname: umair
  default_platform: Ruby 2.3 (Puma)
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
container-commands:
  01_db_create:
    command: rake db:create
    leader_only: true
  02_db_crmigrate:
    command: rake db:migrate
    leader_only: true
  03_compile_assets:
    command: rake assets:precompile
    leader_only: false
