branch-defaults:
  limits:
    environment: production
    group_suffix: null
global:
  application_name: idt-production
  branch: master
  default_ec2_keyname: umair
  default_platform: Ruby 2.3 (Puma)
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
packages:
  yum:
    git: []
