# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.3-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Dockerize
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev
            sudo apt-get install -y zlib1g-dev libicu-dev g++
            sudo apt-get install mysql-client
            sudo apt-get -y install mysql-server

      - run:
           name: Start database server
           command: |
             sudo service mysql start
             sleep 2
             ps aux | grep mysql
      - run:
           name: Start database server
           command: |
             sudo cat /etc/mysql/debian.cnf
      - run:
           name: Start database server
           command: |
             export DEBIAN_FRONTEND=noninteractive
             sudo apt-get -y remove mysql-server
             sudo apt-get -y autoremove
             sudo apt-get -y install software-properties-common
             sudo apt-add-repository -y 'deb http://ppa.launchpad.net/ondrej/mysql-experimental/ubuntu precise main'
             sudo apt-get update
             sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password "root"'
             sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password "root"'
             sudo apt-get -y install mysql-server
      - run:
           name: Start database server
           command: |
             sudo cat /etc/mysql/debian.cnf


      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: |-
           mkdir -p config && echo 'test:
              adapter: mysql2
              database: circle_ruby_test
              username: root
              password:
              host: localhost
              port: 3306
              socket: /var/run/mysqld/mysqld.sock
           ' > config/database.yml

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: RAILS_ENV=test bundle exec rake db:create
      - run: RAILS_ENV=test bundle exec rake db:schema:load

      # run tests!
      - run:
          name: bundle exec rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
