default: &default
  adapter: mysql2
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 10 } %>
  database: <%= ENV.fetch('DB_NAME')  {'dialuck_dev'}%>
  port: <%= ENV.fetch('DB_PORT') { 3360 } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '123' } %>

development:
  <<: *default


test:
  <<: *default
  database: dialuck_test

staging:
  <<: *default
production:
  <<: *default



