# default: &default
#   adapter: postgresql
#   host: localhost
#   encoding: unicode
#   pool: 50
#   port: 5432
#   username: postgres
#   password: 12345678

# development:
#   <<: *default
#   database: dialuck_development

default: &default
 adapter: mysql2
 host: localhost
 # encoding: unicode
 pool: 50
 port: 5432
 username: root
 password: 12345678
 socket: /var/run/mysqld/mysqld.sock

development:
 <<: *default
 database: dialuck_development
